apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

commonAnnotations:
  argocd.argoproj.io/sync-options: "Replace=true"
    
# Which resources to include
configMapGenerator:
  - name: grafana-istio-dashboards
    files:
      - dashboards/istio/istio-mesh-7639.json    # External file
      - dashboards/istio/istio-service-7636.json    # External file
      - dashboards/istio/istio-workload-7630.json    # External file
    options:
      disableNameSuffixHash: true

